lithnet.activedirectory.passwordchange.web/Models/PasswordChangeRequestModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using Resources;

namespace Lithnet.ActiveDirectory.PasswordChange.Web.Models
{
    [Localizable(true)]
    public class PasswordChangeRequestModel
    {
        [Required(ErrorMessageResourceType = typeof(UIMessages), ErrorMessageResourceName = "UserNameIsRequired")]
        public string UserName { get; set; }

        [AllowHtml]
        [Required(ErrorMessageResourceType = typeof(UIMessages), ErrorMessageResourceName = "CurrentPasswordIsRequired")]
        public string CurrentPassword { get; set; }

        [AllowHtml]
        [Required(ErrorMessageResourceType = typeof(UIMessages), ErrorMessageResourceName = "NewPasswordIsRequired")]
        public string NewPassword { get; set; }

        [AllowHtml]
        [Required(ErrorMessageResourceType = typeof(UIMessages), ErrorMessageResourceName = "ConfirmPasswordIsRequired")]
        public string ConfirmNewPassword { get; set; }

        public bool Success { get; set; }

        public string Redirect { get; set; }
    }
}

lithnet.activedirectory.passwordchange.web/Controllers/ChangeController.cs
using System;
using System.Configuration;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.DirectoryServices.AccountManagement;
using System.Linq;
using System.Text;
using Lithnet.ActiveDirectory.PasswordChange.Web.Exceptions;
using Lithnet.ActiveDirectory.PasswordChange.Web.Models;
using NLog;

namespace Lithnet.ActiveDirectory.PasswordChange.Web.Controllers
{
    public class ChangeController : Controller
    {
        private readonly IPasswordManager passwordManager;

        private readonly RateLimiter rateLimiter;

        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        public ChangeController(IPasswordManager passwordManager, RateLimiter rateLimiter)
        {
            this.passwordManager = passwordManager;
            this.rateLimiter = rateLimiter;
        }

        public ActionResult Do(string username, string redirect)
        {
            try
            {
                if (ConfigurationManager.AppSettings["logHeaders"] == "true")
                {
                    StringBuilder message = new StringBuilder();
                    message.AppendLine("--------------------");
                    message.AppendLine($"Request from: {this.Request.UserHostAddress}");
                    foreach (string key in this.Request.Headers.Keys)
                    {
                        message.AppendLine($"{key}: {this.Request.Headers.Get(key)}");
                    }

                    message.AppendLine("--------------------");
                    Logger.Trace(message.ToString());
                }

                this.rateLimiter.ThrowOnRateLimitExceeded(username, this.Request);

                PasswordChangeRequestModel pageModel = new PasswordChangeRequestModel();

                if (!string.IsNullOrEmpty(username))
                {
                    pageModel.UserName = this.Server.HtmlEncode(username);
                }

                if (!string.IsNullOrEmpty(redirect))
                {
                    redirect = this.Server.HtmlEncode(redirect);
                    if (this.ValidRedirectUri(redirect))
                    {
                        pageModel.Redirect = redirect;
                    }
                }

                if (!this.ModelState.IsValid)
                {
                    return this.View(pageModel);
                }

                return this.View(pageModel);
            }
            catch (RateLimitExceededException ex)
            {
                Logger.Error(ex);
                return this.View("RateLimitExceeded");
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "An unhandled exception occurred in Do");
                return this.View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Do(PasswordChangeRequestModel model)
        {
            try
            {
                this.rateLimiter.ThrowOnRateLimitExceeded(model.UserName, this.Request);

                if (!this.ModelState.IsValid)
                {
                    return this.View(model);
                }

                if (model.NewPassword != model.ConfirmNewPassword)
                {
                    this.ModelState.AddModelError(nameof(model.ConfirmNewPassword), Resources.UIMessages.PasswordsDoNotMatch);
                    return this.View(model);
                }

                PasswordTestResult result = await this.passwordManager.TestPassword(model.UserName, model.NewPassword).ConfigureAwait(false);

                if (result.Code != PasswordTestResultCode.Approved)
                {
                    this.ModelState.AddModelError(nameof(model.ConfirmNewPassword), result.ToString());
                    return this.View(model);
                }

                await this.ChangePassword(model.UserName, model.CurrentPassword, model.NewPassword).ConfigureAwait(false);
                model.Success = true;

                if (model.Redirect != null)
                {
                    if (this.ValidRedirectUri(model.Redirect))
                    {
                        return new RedirectResult(model.Redirect);
                    }
                    else
                    {
                        model.Redirect = null;
                    }
                }

                return this.View("Success");
            }
            catch (NotFoundException)
            {
                Logger.Error($"The password change attempt for user {model.UserName} failed because the user was not found in the directory");
                this.ModelState.AddModelError(nameof(model.CurrentPassword), Resources.UIMessages.InvalidUserOrPassword);
                return this.View(model);
            }
            catch (PasswordIncorrectException)
            {
                Logger.Error($"The password change attempt for user {model.UserName} failed because the current password was incorrect");
                this.ModelState.AddModelError(nameof(model.CurrentPassword), Resources.UIMessages.InvalidUserOrPassword);
                return this.View(model);
            }
            catch (PasswordDoesNotMeetPolicyException)
            {
                Logger.Error($"The password change attempt for user {model.UserName} failed because AD rejected the password change");
                this.ModelState.AddModelError(nameof(model.ConfirmNewPassword), Resources.UIMessages.PasswordRejectedByAdPolicy);
                return this.View(model);
            }
            catch (RateLimitExceededException ex)
            {
                Logger.Error(ex.Message);
                return this.View("RateLimitExceeded");
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "An unhandled exception occurred when attempting the password change");
                this.ModelState.AddModelError(nameof(model.ConfirmNewPassword), Resources.UIMessages.UnhandledError);
                return this.View(model);
            }
        }

        public ActionResult Success()
        {
            return this.View();
        }

        public ActionResult SuccessEnd()
        {
            return this.View();
        }

        private async Task ChangePassword(string username, string oldPassword, string newPassword)
        {
            UserPrincipal userPrincipal = await WindowsSamController.GetUserPrincipal(username);
            await WindowsSamController.ChangeUserPassword(userPrincipal, oldPassword, newPassword);
        }

        private bool ValidRedirectUri(string uri)
        {
            return PasswordChangeConfigSection.Configuration.AllowedReturnUrls.OfType<AllowedReturnUrlElement>().Any(t => string.Equals(t.Value, uri, StringComparison.OrdinalIgnoreCase));
        }
    }
}

lithnet.activedirectory.passwordchange.web/Views/Change/Do.cshtml
@{
    ViewBag.Title = PasswordChangeConfigSection.Configuration.Branding.Header;
}

@model Lithnet.ActiveDirectory.PasswordChange.Web.Models.PasswordChangeRequestModel

@section Instructions {
    @if (File.Exists(Server.MapPath("~/App_Data/Templates/instructions.html")))
    {
        <section class="instructions" aria-label="password instructions">
            <h5 class="instructions-header">@Resources.Do.HeadingInstructions</h5>
            <div class="instructions-content">

                @Html.Raw(File.ReadAllText(Server.MapPath("~/App_Data/Templates/instructions.html")))

            </div>
        </section>
    }
}

@section FurtherNotes {
    @if (File.Exists(Server.MapPath("~/App_Data/Templates/notes.html")))
    {
        <section class="notes" aria-label="further notes">
            <h5 class="notes-header">@Resources.Do.HeadingNotes</h5>
            <div class="notes-content">
                @Html.Raw(File.ReadAllText(Server.MapPath("~/App_Data/Templates/notes.html")))
            </div>
        </section>
    }
}

@{
    Dictionary<string, object> usernameProps = new Dictionary<string, object>
{
{"class", "form-control"},
{"placeholder", ConfigurationManager.AppSettings["username-only"] == "true" ? Resources.Do.UserName : Resources.Do.UserNameOrEmail},
{"id", "user-name"},
{"aria_label", ConfigurationManager.AppSettings["username-only"] == "true" ? Resources.Do.UserName : Resources.Do.UserNameOrEmail},
{"required", true},
};

    Dictionary<string, object> currPasswordProps = new Dictionary<string, object>
{
{ "class", "form-control" },
{ "placeholder", Resources.Do.CurrentPassword },
{ "id", "current-password" },
{ "aria_label", Resources.Do.CurrentPassword },
{ "required", true }
};

    Dictionary<string, object> newPasswordProps = new Dictionary<string, object>
{
{"class", "form-control"},
{"placeholder", Resources.Do.NewPassword},
{"id", "new-password-input"},
{"aria_label", Resources.Do.NewPassword},
{"required", true}
};

    Dictionary<string, object> confimNewPasswordProps = new Dictionary<string, object>
{
{"class", "form-control"},
{"placeholder", Resources.Do.ConfirmNewPassword},
{"id", "confirm-new-password-input"},
{"aria_label", Resources.Do.ConfirmNewPassword},
{"required", true}
};

    // Username

    bool usernameError = ViewData.ModelState[nameof(Model.UserName)] != null && ViewData.ModelState[nameof(Model.UserName)].Errors.Any();

    if (usernameError)
    {
        usernameProps.AddOrReplace("aria_invalid", true);
        usernameProps.AddOrReplace("aria_describedby", "usernameErrorDescription");
        usernameProps.AddOrReplace("autofocus", true);
    }

    if (string.IsNullOrEmpty(Model?.UserName))
    {
        usernameProps.AddOrReplace("autofocus", true);
    }

    // Current password

    bool currPasswordError = ViewData.ModelState[nameof(Model.CurrentPassword)] != null && ViewData.ModelState[nameof(Model.CurrentPassword)].Errors.Any();

    if (currPasswordError)
    {
        currPasswordProps.AddOrReplace("aria_invalid", true);
        currPasswordProps.AddOrReplace("aria_describedby", "currentPasswordErrorDescription");

        currPasswordProps.AddOrReplace("autofocus", true);
    }

    if (!string.IsNullOrEmpty(Model?.UserName) && !string.IsNullOrEmpty(Model?.CurrentPassword))
    {
        currPasswordProps.AddOrReplace("value", Model.CurrentPassword);
    }
    else if (string.IsNullOrEmpty(Model?.CurrentPassword))
    {
        currPasswordProps.AddOrReplace("autofocus", true);
    }

    // New password

    bool newPasswordError = ViewData.ModelState[nameof(Model.NewPassword)] != null && ViewData.ModelState[nameof(Model.NewPassword)].Errors.Any();

    if (newPasswordError)
    {
        newPasswordProps.AddOrReplace("aria_describedby", "newPasswordErrorDescription");
        newPasswordProps.AddOrReplace("aria_invalid", true);
        newPasswordProps.AddOrReplace("autofocus", true);
    }

    // Confirm new password

    bool confirmPasswordError = ViewData.ModelState[nameof(Model.ConfirmNewPassword)] != null && ViewData.ModelState[nameof(Model.ConfirmNewPassword)].Errors.Any();

    if (confirmPasswordError)
    {
        confimNewPasswordProps.AddOrReplace("aria_invalid", true);
        confimNewPasswordProps.AddOrReplace("aria_describedby", "confirmNewPasswordErrorDescription");
        newPasswordProps.AddOrReplace("autofocus", true);
    }
}

@using (Html.BeginForm("Do", "Change", FormMethod.Post))
{
    <h5>@Resources.Do.CurrentDetails</h5>
    <div class="form-section" area-label="password change form">
        <div class="form-row">
            <div class="form-group col-md-6 mr-auto ml-auto">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                    </div>

                    @Html.TextBoxFor(model => model.UserName, usernameProps)
                </div>
                @if (usernameError)
                {
                    <div class="alert alert-danger field-alert" role="alert">
                        <i class="fa fa-exclamation-circle"></i> @Html.ValidationMessageFor(model => model.UserName, null, new { @id = "usernameErrorDescription" })
                    </div>
                }
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mr-auto ml-auto">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-lock"></i></span>
                    </div>

                    @Html.PasswordFor(model => model.CurrentPassword, currPasswordProps)
                </div>

                @if (currPasswordError)
                {
                    <div class="alert alert-danger field-alert" role="alert">
                        <i class="fa fa-exclamation-circle"></i> @Html.ValidationMessageFor(model => model.CurrentPassword, null, new { @id = "currentPasswordErrorDescription" })
                    </div>
                }
            </div>
        </div>
    </div>
    <h5>@Resources.Do.NewDetails</h5>
    <div class="form-section">
        <div class="form-row">
            <div class="form-group col-md-6 mr-auto ml-auto">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-chevron-right"></i></span>
                    </div>
                    @Html.PasswordFor(model => model.NewPassword, newPasswordProps)
                </div>

                @if (newPasswordError)
                {
                    <div class="alert alert-danger field-alert" role="alert">
                        <i class="fa fa-exclamation-circle"></i> @Html.ValidationMessageFor(model => model.NewPassword, null, new { @id = "newPassowrdErrorDescription" })
                    </div>
                }
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mr-auto ml-auto">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-chevron-right"></i></span>
                    </div>

                    @Html.PasswordFor(model => model.ConfirmNewPassword, confimNewPasswordProps)
                </div>

                @if (confirmPasswordError)
                {
                    <div class="alert alert-danger field-alert" role="alert">
                        <i class="fa fa-exclamation-circle"></i> @Html.ValidationMessageFor(model => model.ConfirmNewPassword, null, new { @id = "confirmNewPasswordErrorDescription" })
                    </div>
                }
            </div>

            @if (Model?.Redirect != null)
            {
                @Html.HiddenFor(model => model.Redirect)
            }
        </div>
    </div>

    <footer>
        <div id="action-buttons">
            @Html.AntiForgeryToken()
            <button type="submit" class="btn btn-primary">@Resources.Do.ButtonRequestChange</button>

            @{
                CustomLinkElement helpLink = PasswordChangeConfigSection.Configuration.CustomLinks.GetHelpLink;
            }

            @if (helpLink != null)
            {
                <a href="@helpLink.LinkUrl" class="btn btn-outline-primary">@helpLink.LinkText</a>
            }
        </div>
    </footer>
}

@section scripts {
    <script src="~/Scripts/do.js"></script>
}

lithnet.activedirectory.passwordchange.web/Views/Change/Success.cshtml
@{
    ViewBag.Title = PasswordChangeConfigSection.Configuration.Branding.Header;
}

@model Lithnet.ActiveDirectory.PasswordChange.Web.Models.PasswordChangeRequestModel

<h5>@Resources.Success.SuccessTitle</h5>
<div class="alert alert-success" role="alert">
    <i class="fa fa-check"></i> @Resources.Success.SuccessMessage
</div>

@{
    CustomLinkElement successLink = PasswordChangeConfigSection.Configuration.CustomLinks.SuccessButton;
}

@if (successLink != null)
{
    <a href="@successLink.LinkUrl" class="btn btn-primary">@successLink.LinkText</a>
}

lithnet.activedirectory.passwordchange.web/Views/Change/SuccessEnd.cshtml
@{
    ViewBag.Title = PasswordChangeConfigSection.Configuration.Branding.Header;
}

@model Lithnet.ActiveDirectory.PasswordChange.Web.Models.PasswordChangeRequestModel

<h5>@Resources.Success.SuccessTitle</h5>
<div class="alert alert-success" role="alert">
    <i class="fa fa-check"></i> @Resources.Success.SuccessMessage
</div>

lithnet.activedirectory.passwordchange.web/Views/Shared/RateLimitExceeded.cshtml
@using System.Configuration
@{
    ViewBag.Title = PasswordChangeConfigSection.Configuration.Branding.Header;
}

<div class="form-container">
    <fieldset>
        <section>
            <b class="error">
                <i class="fas fa-exclamation-circle"></i> Too many requests
            </b>
        </section>
    </fieldset>
</div>

lithnet.activedirectory.passwordchange.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/fontawesome")
</head>
<body>

    <div id="page">
        <header>
            <div class="header" role="banner">
                <img class="logo" src="~/Content/images/logo.png" alt="@PasswordChangeConfigSection.Configuration.Branding.CompanyName"/>
                <h1 class="title">@PasswordChangeConfigSection.Configuration.Branding.AppName</h1>
            </div>
        </header>

        <div class="content">
            @RenderSection("Instructions", required: false)
            @RenderBody()
            @RenderSection("FurtherNotes", required: false)
        </div>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>